server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/zhixiang?&serverTimezone=GMT%2B8
    username: root
    password: cll123456
    database-platform: org.hibernate.dialect.MySQL5Dialect
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    username: chenmioyui@qq.com
    host: smtp.qq.com
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  thymeleaf:
    cache: false
qqwry:
  dat:
    path: E:/study/Gitee/demo/src/main/resources/static/qqwry.dat

